### ISSUE TITLE
백트래킹에서 call stack size 초과하는 문제 발생

### ISSUE THREAD

**Issue by cjnghn** [cjnghn/next-sem#2]
```
/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38
      this.backtrack(currentTimetable, index + 1, currentCredits, result, limit)
           ^
RangeError: Maximum call stack size exceeded
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
    at TimeTableGenerator.backtrack (/Users/matcha/hack/next-sem/src/core/TimeTableGenerator.ts:38:12)
```

**Comment by cjnghn** [comment]
재귀 호출을 스택 기반으로 고쳐서 수정할 수 있었음.
